name: binary
on:
  push:
    tags: [v*]
jobs:
  binary:
    permissions: write-all
    strategy:
      matrix:
        kind: [linux, linux-x64, osx, osx-arm64, windows, windows-x64]
        include:
          - kind: linux
            os: ubuntu-latest
            config: -p:PublishSingleFile=true -p:SelfContained=false -r linux-x64
            upload: linux-x64/publish/difflytic-linux
          - kind: linux-x64
            os: ubuntu-latest
            config: -p:PublishAot=true -r linux-x64
            upload: linux-x64/publish/difflytic-linux-x64
          - kind: osx
            os: macos-latest
            config: -p:PublishSingleFile=true -p:SelfContained=false -r osx-arm64
            upload: osx-arm64/publish/difflytic-osx
          - kind: osx-arm64
            os: macos-latest
            config: -p:PublishAot=true -r osx-arm64
            upload: osx-arm64/publish/difflytic-osx-arm64
          - kind: windows
            os: windows-latest
            config: -p:PublishSingleFile=true -p:SelfContained=false -r win-x64
            upload: win-x64/publish/difflytic-win.exe
          - kind: windows-x64
            os: windows-latest
            config: -p:PublishAot=true -r win-x64
            upload: win-x64/publish/difflytic-win-x64.exe
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.302
      - name: Restore
        run: dotnet restore src/Difflytic.Cli
      - name: Build
        run: dotnet publish src/Difflytic.Cli -c Release ${{matrix.config}}
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: src/Difflytic.Cli/bin/Release/net8.0/${{matrix.upload}}
