name: build
on:
  push:
    tags: [v*]
jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        kind: [linux, macos-arm64, macos-x64, windows]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
            file: difflytic-linux-x64
          - kind: macos-arm64
            os: macos-latest
            target: osx-arm64
            file: difflytic-macos-arm64
          - kind: macos-x64
            os: macos-latest-large
            target: osx-x64
            file: difflytic-macos-x64
          - kind: windows
            os: windows-latest
            target: win-x64
            file: difflytic-win-x64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.302
      - name: Restore
        run: dotnet restore src
      - name: Build
        run: dotnet publish src -c Release -r ${{ matrix.target }}
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: src/Difflytic.Cli/bin/Release/net8.0/${{ matrix.target }}/publish/${{ matrix.file }}
